dataset: "OccScanNet" # "NYU", "OccScanNet"

n_relations: 4

enable_log: true

logdir: "/mnt/vdb1/hongxiao.yu/logs/ISO_occscannet_logs/"


fp_loss: true 
frustum_size: 8 
batch_size: 1
n_gpus: 1
num_workers_per_gpu: 0
exp_prefix: "iso"
run: 1
lr: 1e-4
weight_decay: 1e-4

context_prior: true

relation_loss: true 
CE_ssc_loss: true
sem_scal_loss: true
geo_scal_loss: true

project_1_2: true
project_1_4: true
project_1_8: true

voxeldepth: true
voxeldepthcfg:
  depth_scale_1: true
  depth_scale_2: false
  depth_scale_4: false
  depth_scale_8: false

use_gt_depth: false
use_zoedepth: false
use_depthanything: true
zoedepth_as_gt: false
depthanything_as_gt: false

add_fusion: true

frozen_encoder: true
